name: "Merge Dependabot PR"

on:
  pull_request:
    types:
      - opened

jobs:
  mvn-test:
    uses: derBobby/java-pipelines/.github/workflows/callable-mvn.yml@v4.0.3
    with:
      mvn-stage: test
  codeql:
    needs: mvn-test
    uses: derBobby/java-pipelines/.github/workflows/callable-codeql.yml@v4.0.3
  merge:
    needs: mvn-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          skip-verification: true
